### PR TITLE
docs: Image link fixed

### PR DESCRIPTION
**Pull request by netzahdzc**
Looked for me that the images references were settled in a different format, thus, I updated them base on a generic mechanism. Minimal but needed improvement; though :P

### CODE REVIEW

**Comment by aarranz** [comment]
Hi @netzahdzc!

First, thanks for taking time for improving WireCloud :smile:.

The user guide is mean to be compiled using MkDocs and provided using [ReadTheDocs](https://wirecloud.readthedocs.io/en/latest/user_guide/). Currently the documentation is rendered correctly on ReadTheDocs, but It's also true that it is rendered incorrectly outside, e.g. when rendering it directly on [GitHub](https://github.com/Wirecloud/wirecloud/blob/develop/docs/user_guide.md).

We need to have the documentation on ReadTheDocs, so we have to find a way to make it render correctly in both worlds.

**Comment by aarranz** [comment]
These are the instructions for building WireCloud's documentation using MkDocs:

```
$ pip install mkdocs wirecloud-markdown-github

$ cd wirecloud-repo
$ mkdocs build --clean
```

Once build, you can open the `site/index.html` file for reading the documentation :smile:.

**Comment by netzahdzc** [comment]
no prob for the editing, it was a pleasure.

Technically I just followed same markdown code the project were using. For instance to display images I used html code as used at: https://github.com/Wirecloud/wirecloud/blob/develop/README.md

If I happened to find a way to facilitate what you referred about readTheDocs I might come back to this issue, meanwhile: regards :-)

**Comment by aarranz** [comment]
For reference. Ticket mkdocs/mkdocs#991 seems to indicate that there is no solution yet.

**Comment by aarranz** [comment]
Closing this PR as it is stalled. If you find any way to make images render correctly on github and on RTD, please open a new PR.

Thank you very much for your effort!

**Pull request closed without merging**
