### PR TITLE
Updated CoNWeT_weather-mashup-example_1.0.2.wgt Widget

### PR DESCRIPTION
**Pull request by manchandavishal**
I have updated CoNWeT_wms-viewer-geowidget_0.5.5.wgt widget config.xml file to resolve following issue:
(https://github.com/Wirecloud/wirecloud/issues/260)

### CODE REVIEW

**Comment by manchandavishal** [comment]
@aarranz  
I am facing a problem related to test case execution on travis tool, I want to inform you that I have already tested my solution on locally and it is working properly.
Please guide me further so that we can close this issue asap.

**Comment by aarranz** [comment]
Hi @manchandavishal,

Sorry for not responding you before, I'm currently a bit busy. Don't worry about the travis fails, as there are no tests directly affected by the weather mashup example, the fails are due problems with the tests itself.

Can you summarise the changes you have made into the weather-mashup-example file?

BR

**Comment by manchandavishal** [comment]
Hi @aarranz I have updated some tags in config.xml file of CoNWeT_wms-viewer-geowidget_0.5.5.wgt widget of CoNWeT_weather-mashup. Earlier Template , Catalog.ResourceDescription, Platform.StateProperties, Platform.Wiring tags are used in config.xml file, Now these tags are replaced with widget, details, persistentvariables, wiring tags respectively.After replacing these tags weather-mashup is working fine on my end and resolve issue #260  please confirm it is Working or not?

**Comment by manchandavishal** [comment]
Hi @aarranz is there any update for this PR.Kindly let me know in case any query so that we can close this issue asap.

**Comment by aarranz** [comment]
Hi @manchandavishal,

sorry for the delay and thank you for the contribution!

BR.

**Pull request merged**
