### PR TITLE
Use a separate ENV variable for Authentication URL is supplied

### PR DESCRIPTION
**Pull request by jason-fox**
Related #392 - This PR offers an alternative `AUTHENTICATION_URL` which means it can be different to the `ACCESS_TOKEN_URL`

The fallback is to use `FIWARE_IDM_SERVER` as previously

### CODE REVIEW

**Comment by aarranz** [comment]
Hi @jason-fox,

Thank you very much for your contributions. I'm missing some minor update on the installation guide regarding this new setting (on the IdM section) as well as some basic test to cover new code lines. I think everything looks great except the name of the setting. I prefer something like `FIWARE_IDM_PUBLIC_URL`. What do you think?

I

**Comment by aarranz** [comment]
Hi @jason-fox, can you proceed an update the environment name?. Miguel is a bit busy to write here, but I've talked with him and he agrees.

**Comment by jason-fox** [comment]
@aarranz - PR has been fixed according to review.
-   parameter has been renamed - 89cbdd2 & https://github.com/Wirecloud/docker-wirecloud/pull/29/commits/0002c51
-  test added - 4867790

**Comment by aarranz** [comment]
Merging, Thank you very much for the contribution!

**Pull request merged**
