### PR TITLE
(ja) Add Japanese documentation

### PR DESCRIPTION
**Pull request by fisuda**
Hi @aarranz,

I have translated the WireCloud documents to Japanese.  I put them into /doc.ja which I newly created.  The folder includes only files translated to Japanese. Please review this PR.

Thanks.

### CODE REVIEW

**Comment by aarranz** [comment]
Hi @fisuda,

I think everything is more or less ok, although I don't understand Japanese 😅. Do you know if there is something to be done to publish your documentation on ReadTheDocs?

Also, take into account the following aspects:

- I'm trying to make some updates to the documentation before I take my paternity leave. Specially, we have to update documentation to talk about the new edit mode and fix some details on the marketplace section. So probably I will ask you to update the Japanese translation.
- We have some code for generating the screenshots for the documentation, so probably is a good idea to create screenshots in Japanese.

In any case, thank you very much for your contributions!

**Comment by fisuda** [comment]
Hi @aarranz,

Thank you for your response.

I'm running my website for Japanese audience (Especially developers) who have an interest in FIWARE.
 - https://www.letsfiware.jp/ 

The documents with regard to WireCloud are in the following links.
 - https://wirecloud.letsfiware.jp/
 - https://fiware-academy.letsfiware.jp/processing/wirecloud/index.html
 - https://open-apis.letsfiware.jp/wirecloud/

> Also, take into account the following aspects:

Of course, I will work on them.

Best regards,

**Comment by aarranz** [comment]
Ok, so let's merge it :)

**Comment by fisuda** [comment]
Thank you for merging it. So Japanese user also can do "Let's wiring" :)

**Pull request merged**
