### PR TITLE
[WIP] (ja) Add Japanese Translation

### PR DESCRIPTION
**Pull request by fisuda**
Hi @aarranz ,

I'm trying to make Wirecloud supporting Japanese language.
Although I made  Japanese message files, I encountered the following issues while testing.

- The basic concepts tutorial hangs up where loading widget.
- The Behaviour Oriented Wiring  tutorial don't start after selecting the menu.
- The messages on Workspace Browser are in English, not in Japanese / Spanish.  

Please give me a advice.

Thanks

### CODE REVIEW

**Comment by aarranz** [comment]
Hi @fisuda,

Thank you very much for your contribution!

and sorry for delay on the response.

> * The basic concepts tutorial hangs up where loading widget.
> * The Behaviour Oriented Wiring tutorial don't start after selecting the menu.

I've been testing and your translations seems not to be affecting tutorials. I think that you problems with tutorials are, probably, not related to the translations itself but with some bug on the tutorials code. Are the tutorial working for you using the english language? What browser are you using for testing?

Captura de pantalla 2019-04-26 a las 10 56 57

> * The messages on Workspace Browser are in English, not in Japanese / Spanish.

I've merged you changes regarding this widget (Wirecloud/workspace-browser-widget#3), maybe you are not seeing the changes as we have to update this widget within WireCloud.  But seems to be working:

Captura de pantalla 2019-04-26 a las 11 04 59

If you are using the development settings, please ensure you have Japanese enable:

```python
LANGUAGES = (
    ('es', 'Spanish'),
    ('en', 'English'),
    ('pt', 'Portuguese'),
    ('ja', 'Japanese'),
)
```

**Comment by fisuda** [comment]
Hi @aarranz,

Thank you so much for taking your precious time for me.

Sorry for lacking my environment information.
I'm using the Chrome browser. Its version is the following.

- Google Chrome version: 73.0.3683.103（Official Build） （64 bit） on Windows 10 and Ubuntu 18.04

My Wirecloud instance is build using 'docker-wirecloud / dev'. I set my repository and branch in the Dockerfile.

- ARG GITHUB_REPOSITORY=fisuda
- ARG SOURCE_BRANCH=JapaneseTranslation

I have tested again. 

- The basic concepts tutorial hangs up where loading widget.

Unfortunately, I haven't been able to reproduce it. This issue was occurred on the condition the widgets haven't been uploaded yet. I will try to check the occurrence condition again.

- The Behaviour Oriented Wiring tutorial don't start after selecting the menu.

The following errors are occurred on the Chrome browser after selecting the menu. And then, the tutorial don't start.

```
iframe.js:835 Uncaught TypeError: Cannot read property 'left' of null
    at Object.setPositions (iframe.js:835)
    at appendTagsAndSendToParent (iframe.js:931)
    at iframe.js:989
    at Array.forEach (<anonymous>)
    at extractAds (iframe.js:969)
    at extractAdsWrapper (iframe.js:960)
    at iframe.js:963
c38a07cc2c9f.js:68 DOMException: Failed to set the 'innerHTML' property on 'Element': The provided markup is invalid XML, and therefore cannot be inserted into an XML document.
    at new SimpleDescription (http://192.168.11.242/static/cache/js/c38a07cc2c9f.js:1583:95)
    at Tutorial.start (http://192.168.11.242/static/cache/js/c38a07cc2c9f.js:1554:1783)
    at TutorialSubMenu._menuItemCallback (http://192.168.11.242/static/cache/js/c38a07cc2c9f.js:376:29)
    at Event.dispatch (http://192.168.11.242/static/cache/js/c38a07cc2c9f.js:68:22)
    at MenuItem.dispatchEvent (http://192.168.11.242/static/cache/js/c38a07cc2c9f.js:71:95)
    at MenuItem.click (http://192.168.11.242/static/cache/js/c38a07cc2c9f.js:366:134)
    at MenuItem.element_onclick (http://192.168.11.242/static/cache/js/c38a07cc2c9f.js:370:628)
```

be

- The messages on Workspace Browser are in English, not in Japanese / Spanish.

The following message remains in English. I think that the Mashup API returns this message. But, I haven't been able to find the cause.

'We couldn't find anything for your search'

ws

**Comment by fisuda** [comment]
Hi @aarranz,

I found the cause for two problems. Please have a look.

- The basic concepts tutorial hangs up where loading widget.

It seems that this problem is not related to the translations.

The following error occurs when using localhost or 127.0.0.1 as a host address.
And then, This tutorial hangs up. This error is not only for 'ja' but also for 'en'.

```
37786b56bae8.js:154 POST http://localhost/api/resources 409 (Conflict)
37786b56bae8.js:154 XHR failed loading: POST "http://localhost/api/resources".
Request @ 37786b56bae8.js:154
makeRequest @ 37786b56bae8.js:158
addComponent @ 37786b56bae8.js:895
addComponent @ 37786b56bae8.js:912
(anonymous) @ 37786b56bae8.js:1565
_activate @ 37786b56bae8.js:1621
activate @ 37786b56bae8.js:1621
setTimeout (async)
nextStep @ 37786b56bae8.js:1555
(anonymous) @ 37786b56bae8.js:1585
dispatch @ 37786b56bae8.js:68
dispatchEvent @ 37786b56bae8.js:71
clickCallback @ 37786b56bae8.js:308
```

- The Behaviour Oriented Wiring tutorial don't start after selecting the menu.

This problem was due to a translation error. https://github.com/Wirecloud/wirecloud/pull/396/commits/e7b69ec629d3d07cc8bee046ea5d13a91258cde0

**Comment by fisuda** [comment]
Hi @aarranz,

- The messages on Workspace Browser are in English, not in Japanese / Spanish.

These error messages have been able to localize to Japanese by updating Workspace Browser widget. 
 https://github.com/Wirecloud/workspace-browser-widget/pull/4

The three issues have been solved. Would you please review this PR?

**Comment by aarranz** [comment]
Hi @fisuda,

On the one hand, I've updated the workspace browser widget to version 0.1.3 on the WireCloud repo 😄.

On the other hand, We've made some updates into the WireCloud repo and I think that some of those changes has modified some messages, could you check if you have to make some update to the Japanese translation? Once updated or confirmed that nothing has to be changed, I'll merge this PR.

Good work 😉.

**Comment by fisuda** [comment]
Hi @aarranz,

As I'm on my way from Genoa to Tokyo, now I can't work on this. Sorry, I will check if you have to make some update, and reply to you on Saturday.

Thank you.

**Comment by fisuda** [comment]
Hi @aarranz, I apologize for the late reply. I updated Japanese messages. Please review this PR.

**Comment by aarranz** [comment]
I think it is ok, so I merged it. I'll work on releasing WireCloud 1.3 in the next weeks (probably in two weeks), so I will notify you if a see any problem.

Thank you very much!

**Pull request merged**
